# CODING TASK #1. IMPORT DATASET AND PERFORM BASIC STATISTICAL DATA ANALYSIS

In [ ]:
# Import Pandas Library
import pandas as pd

In [ ]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/335 Machine Learning/04-Data Wrangling  EDA with Pandas/"

/content/drive/MyDrive/Colab Notebooks/335 Machine Learning/04-Data Wrangling  EDA with Pandas

In [ ]:
# Let's read a CSV file using Pandas as follows
hr_df = pd.read_csv('04-2-Human_Resources.csv')
hr_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.0,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,...,3,80,1,17,3,3,5,2,0,3
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,...,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,...,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,...,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,...,1,80,0,6,3,4,4,3,1,2

In [1]:
# Let's obtain the datatype
type(hr_df)

NameError: ignored

In [ ]:
# you can view the first couple of rows using .head()
hr_df.head(6)

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
5,32,3068.0,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,...,3,80,0,8,2,2,7,7,3,6

In [ ]:
# you can view the last couple of rows using .tail()
hr_df.tail(4)

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,...,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,...,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,...,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
# Calculate the average values for employee_df dataframe
hr_df.mean()

<ipython-input-9-859ebac24a6a>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  hr_df.mean()

Age                            36.923810
MonthlyIncome                6505.155419
DailyRate                     802.485714
DistanceFromHome                9.192517
Education                       2.912925
EmployeeCount                   1.000000
EmployeeNumber               1025.556161
EnvironmentSatisfaction         2.721769
HourlyRate                     65.891156
JobInvolvement                  2.729932
JobLevel                        2.063946
JobSatisfaction                 2.728571
MonthlyRate                 14310.966621
NumCompaniesWorked              2.693197
PercentSalaryHike              15.206263
PerformanceRating               3.153165
RelationshipSatisfaction        2.712245
StandardHours                  80.000000
StockOptionLevel                0.793878
TotalWorkingYears              11.279592
TrainingTimesLastYear           2.799320
WorkLifeBalance                 2.761224
YearsAtCompany                  7.008163
YearsInCurrentRole              4.229252
YearsSinceLastPromotion         2.187755
YearsWithCurrManager            4.123129
dtype: float64

In [ ]:
# 35 features in total
hr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   MonthlyIncome             1467 non-null   float64
 2   Attrition                 1470 non-null   object
 3   BusinessTravel            1470 non-null   object
 4   DailyRate                 1470 non-null   int64
 5   Department                1469 non-null   object
 6   DistanceFromHome          1470 non-null   int64
 7   Education                 1470 non-null   int64
 8   EducationField            1469 non-null   object
 9   EmployeeCount             1470 non-null   int64
 10  EmployeeNumber            1469 non-null   float64
 11  EnvironmentSatisfaction   1470 non-null   int64
 12  Gender                    1469 non-null   object
 13  HourlyRate                1470 non-null   int64
 14  JobInvolvement            1470 non-null   int64
 15  JobLevel                  1470 non-null   int64
 16  JobRole                   1469 non-null   object
 17  JobSatisfaction           1470 non-null   int64
 18  MaritalStatus             1469 non-null   object
 19  MonthlyRate               1468 non-null   float64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1469 non-null   float64
 24  PerformanceRating         1469 non-null   float64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(5), int64(21), object(9)
memory usage: 402.1+ KB

In [ ]:
# Obtain a Statistical Summary about the data
hr_df.describe()

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1467.000000,1470.000000,1470.000000,1470.000000,1470.0,1469.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,6505.155419,802.485714,9.192517,2.912925,1.0,1025.556161,2.721769,65.891156,2.729932,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,4711.297846,403.509100,8.106864,1.024165,0.0,601.646166,1.093082,20.329428,0.711561,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,1009.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,2911.000000,465.000000,2.000000,2.000000,1.0,492.000000,2.000000,48.000000,2.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,4908.000000,802.000000,7.000000,3.000000,1.0,1022.000000,3.000000,66.000000,3.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,8378.000000,1157.000000,14.000000,4.000000,1.0,1556.000000,4.000000,83.750000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,19999.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

**PRACTICE OPPORTUNITY #1 [OPTIONAL]:**
- **Calculate the mean, maximum and minimum employee age considered in this study using a different strategy**

# CODING TASK #2. DEALING WITH MISSING DATA

In [ ]:
hr_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.0,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,...,3,80,1,17,3,3,5,2,0,3
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,...,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,...,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,...,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
# Let's locate rows that have Null values
# Notice Row index 6 has many missing values
hr_df.isnull()

Age                         0
MonthlyIncome               3
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  1
DistanceFromHome            0
Education                   0
EducationField              1
EmployeeCount               0
EmployeeNumber              1
EnvironmentSatisfaction     0
Gender                      1
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     1
JobSatisfaction             0
MaritalStatus               1
MonthlyRate                 2
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           1
PerformanceRating           1
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
# Let's see the total number of missing elements per column
hr_df.isnull().sum()

Age                         0
MonthlyIncome               3
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  1
DistanceFromHome            0
Education                   0
EducationField              1
EmployeeCount               0
EmployeeNumber              1
EnvironmentSatisfaction     0
Gender                      1
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     1
JobSatisfaction             0
MaritalStatus               1
MonthlyRate                 2
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           1
PerformanceRating           1
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
# Drop any row that contains a Null value
# Note that the size of the dataframe has been reduced by 7 elements from 1470 to 1463
hr_df.dropna(how = 'any', inplace = True)

In [ ]:
# Notice that row 1 for example is no longer existing!
hr_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
5,32,3068.0,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,...,3,80,0,8,2,2,7,7,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.0,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,...,3,80,1,17,3,3,5,2,0,3
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,...,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,...,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,...,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
# Let's check if we still have any missing values
hr_df.isnull().sum()

Age                         0
MonthlyIncome               0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
# Let's explore an alternative (smarter) method to deal with missing values
# Let's read the raw data again using Pandas as follows
hr_df = pd.read_csv('04-2-Human_Resources.csv')
hr_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.0,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,...,3,80,1,17,3,3,5,2,0,3
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,...,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,...,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,...,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
# Calculate the average monthly income
hr_df['MonthlyIncome'].mean()

6505.155419222904

In [ ]:
# You can use Fillna to fill a given column with a certain value
hr_df["MonthlyIncome"].fillna(hr_df['MonthlyIncome'].mean(), inplace = True)

In [ ]:
hr_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.000000,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,49,6505.155419,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,37,2090.000000,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,33,2909.000000,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,27,3468.000000,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.000000,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,...,3,80,1,17,3,3,5,2,0,3
1466,39,9991.000000,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,...,1,80,1,9,5,3,7,7,1,7
1467,27,6142.000000,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,...,2,80,1,6,0,3,6,2,0,3
1468,49,5390.000000,No,Travel_Frequently,1023,Sales,2,3,Medical,1,...,4,80,0,17,3,2,9,6,0,8
1469,34,4404.000000,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,...,1,80,0,6,3,4,4,3,1,2

**PRACTICE OPPORTUNITY #2 [OPTIONAL]:**
- **Calculate the median monthly rate. Use the calculated median values to fill out missing data. Confirm that the process is successful**

In [ ]:
# Let's read a CSV file using Pandas as follows
employee_df = pd.read_csv('04-2-Human_Resources.csv')
employee_df['MonthlyRate']

0       19479.0
1       24907.0
2        2396.0
3       23159.0
4       16632.0
         ...
1465    12290.0
1466    21457.0
1467     5174.0
1468    13243.0
1469    10228.0
Name: MonthlyRate, Length: 1470, dtype: float64

In [ ]:
# first, let's locate rows that have Null values
employee_df.isnull().sum()

Age                         0
MonthlyIncome               3
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  1
DistanceFromHome            0
Education                   0
EducationField              1
EmployeeCount               0
EmployeeNumber              1
EnvironmentSatisfaction     0
Gender                      1
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     1
JobSatisfaction             0
MaritalStatus               1
MonthlyRate                 2
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           1
PerformanceRating           1
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
# Calculate the average monthly income
employee_df['MonthlyRate'].median()

14235.5

In [ ]:
# You can use Fillna to fill a given column with a certain value
employee_df['MonthlyRate'].fillna(employee_df['MonthlyRate'].median(), inplace = True)

In [ ]:
# first, let's locate rows that have Null values
employee_df.isnull().sum()

Age                         0
MonthlyIncome               3
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  1
DistanceFromHome            0
Education                   0
EducationField              1
EmployeeCount               0
EmployeeNumber              1
EnvironmentSatisfaction     0
Gender                      1
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     1
JobSatisfaction             0
MaritalStatus               1
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           1
PerformanceRating           1
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
employee_df['MonthlyRate']

0       19479.0
1       24907.0
2        2396.0
3       23159.0
4       16632.0
         ...
1465    12290.0
1466    21457.0
1467     5174.0
1468    13243.0
1469    10228.0
Name: MonthlyRate, Length: 1470, dtype: float64

# CODING TASK #3: PERFORM ONE-HOT ENCODING

![2.png]()

![1.png]()

In [ ]:
# Let's read a CSV file using Pandas as follows
hr_df = pd.read_csv('04-2-Human_Resources.csv')
hr_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.0,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,...,3,80,1,17,3,3,5,2,0,3
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,...,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,...,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,...,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
hr_df['BusinessTravel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [ ]:
hr_df['BusinessTravel']

0           Travel_Rarely
1       Travel_Frequently
2           Travel_Rarely
3       Travel_Frequently
4           Travel_Rarely
              ...
1465    Travel_Frequently
1466        Travel_Rarely
1467        Travel_Rarely
1468    Travel_Frequently
1469        Travel_Rarely
Name: BusinessTravel, Length: 1470, dtype: object

In [ ]:
BusinessTravel_Encoded = pd.get_dummies(hr_df['BusinessTravel'])
print(BusinessTravel_Encoded)

      Non-Travel  Travel_Frequently  Travel_Rarely
0              0                  0              1
1              0                  1              0
2              0                  0              1
3              0                  1              0
4              0                  0              1
...          ...                ...            ...
1465           0                  1              0
1466           0                  0              1
1467           0                  0              1
1468           0                  1              0
1469           0                  0              1

[1470 rows x 3 columns]

**PRACTICE OPPORTUNITY #3 [OPTIONAL]:**
- **Import the Human Resources data and remove all missing values**
- **How many unique categories exist in the Education Field column?**
- **Perform one hot encoding to the Education Field column**

In [ ]:
# Let's read a CSV file using Pandas as follows
hr_df = pd.read_csv('04-2-Human_Resources.csv')
hr_df.dropna(how = 'any', inplace = True)

In [ ]:
hr_df['EducationField'].unique()

array(['Life Sciences', 'Other', 'Medical', 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [ ]:
EducationField_Encoded = pd.get_dummies(hr_df['EducationField'])
EducationField_Encoded

,Human Resources,Life Sciences,Marketing,Medical,Other,Technical Degree
0,0,1,0,0,0,0
2,0,0,0,0,1,0
3,0,1,0,0,0,0
4,0,0,0,1,0,0
5,0,1,0,0,0,0
...,...,...,...,...,...,...
1465,0,0,0,1,0,0
1466,0,0,0,1,0,0
1467,0,1,0,0,0,0
1468,0,0,0,1,0,0
1469,0,0,0,1,0,0

# CODING TASK #4: PERFORM SCALING (NORMALIZATION & STANDARDIZATION)

![image.png]()

In [ ]:
# Let's read a CSV file using Pandas as follows
hr_df = pd.read_csv('04-2-Human_Resources.csv')
hr_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.0,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,...,3,80,1,17,3,3,5,2,0,3
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,...,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,...,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,...,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
hr_df.describe().round(2)

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1463.00,1463.00,1463.00,1463.00,1463.00,1463.0,1463.00,1463.00,1463.00,1463.00,...,1463.00,1463.0,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00
mean,0.00,6514.97,802.11,9.18,2.92,1.0,1028.72,2.72,65.86,2.73,...,2.71,80.0,0.79,11.30,2.80,2.76,7.02,4.23,2.19,4.13
std,1.00,4713.52,403.46,8.11,1.02,0.0,600.06,1.09,20.33,0.71,...,1.08,0.0,0.85,7.78,1.29,0.71,6.13,3.62,3.23,3.57
min,-2.08,1009.00,102.00,1.00,1.00,1.0,1.00,1.00,30.00,1.00,...,1.00,80.0,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00
25%,-0.76,2918.50,465.00,2.00,2.00,1.0,495.50,2.00,48.00,2.00,...,2.00,80.0,0.00,6.00,2.00,2.00,3.00,2.00,0.00,2.00
50%,-0.10,4936.00,802.00,7.00,3.00,1.0,1025.00,3.00,66.00,3.00,...,3.00,80.0,1.00,10.00,3.00,3.00,5.00,3.00,1.00,3.00
75%,0.67,8380.50,1157.00,14.00,4.00,1.0,1557.50,4.00,83.50,3.00,...,4.00,80.0,1.00,15.00,3.00,3.00,9.00,7.00,3.00,7.00
max,2.54,19999.00,1499.00,29.00,5.00,1.0,2068.00,4.00,100.00,4.00,...,4.00,80.0,3.00,40.00,6.00,4.00,40.00,18.00,15.00,17.00

In [ ]:
hr_df['Age'].values

array([41, 37, 33, ..., 27, 49, 34])

In [ ]:
# Normalization is conducted to make feature values range from 0 to 1
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
hr_df['Age'] = scaler.fit_transform(hr_df['Age'].values.reshape(-1,1))  #reshape to column view

In [ ]:
hr_df['Age']

0       41
2       37
3       33
4       27
5       32
        ..
1465    36
1466    39
1467    27
1468    49
1469    34
Name: Age, Length: 1463, dtype: int64

In [ ]:
hr_df.describe().round(2)

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1463.00,1463.00,1463.00,1463.00,1463.00,1463.0,1463.00,1463.00,1463.00,1463.00,...,1463.00,1463.0,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00
mean,0.45,6514.97,802.11,9.18,2.92,1.0,1028.72,2.72,65.86,2.73,...,2.71,80.0,0.79,11.30,2.80,2.76,7.02,4.23,2.19,4.13
std,0.22,4713.52,403.46,8.11,1.02,0.0,600.06,1.09,20.33,0.71,...,1.08,0.0,0.85,7.78,1.29,0.71,6.13,3.62,3.23,3.57
min,0.00,1009.00,102.00,1.00,1.00,1.0,1.00,1.00,30.00,1.00,...,1.00,80.0,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00
25%,0.29,2918.50,465.00,2.00,2.00,1.0,495.50,2.00,48.00,2.00,...,2.00,80.0,0.00,6.00,2.00,2.00,3.00,2.00,0.00,2.00
50%,0.43,4936.00,802.00,7.00,3.00,1.0,1025.00,3.00,66.00,3.00,...,3.00,80.0,1.00,10.00,3.00,3.00,5.00,3.00,1.00,3.00
75%,0.60,8380.50,1157.00,14.00,4.00,1.0,1557.50,4.00,83.50,3.00,...,4.00,80.0,1.00,15.00,3.00,3.00,9.00,7.00,3.00,7.00
max,1.00,19999.00,1499.00,29.00,5.00,1.0,2068.00,4.00,100.00,4.00,...,4.00,80.0,3.00,40.00,6.00,4.00,40.00,18.00,15.00,17.00

**PRACTICE OPPORTUNITY #4 [OPTIONAL]:**
- **Perform feature scaling by performing standardization (Recall that Standardization is conducted to transform the data to have a mean of zero and standard deviation of 1.**
- **Perform a sanity check to ensure that the transformation was successful**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
hr_df['Age'] = scaler.fit_transform(hr_df['Age'].values.reshape(-1,1))

In [ ]:
hr_df.describe().round(2)

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1463.00,1463.00,1463.00,1463.00,1463.00,1463.0,1463.00,1463.00,1463.00,1463.00,...,1463.00,1463.0,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00,1463.00
mean,0.45,6514.97,802.11,9.18,2.92,1.0,1028.72,2.72,65.86,2.73,...,2.71,80.0,0.79,11.30,2.80,2.76,7.02,4.23,2.19,4.13
std,0.22,4713.52,403.46,8.11,1.02,0.0,600.06,1.09,20.33,0.71,...,1.08,0.0,0.85,7.78,1.29,0.71,6.13,3.62,3.23,3.57
min,0.00,1009.00,102.00,1.00,1.00,1.0,1.00,1.00,30.00,1.00,...,1.00,80.0,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00
25%,0.29,2918.50,465.00,2.00,2.00,1.0,495.50,2.00,48.00,2.00,...,2.00,80.0,0.00,6.00,2.00,2.00,3.00,2.00,0.00,2.00
50%,0.43,4936.00,802.00,7.00,3.00,1.0,1025.00,3.00,66.00,3.00,...,3.00,80.0,1.00,10.00,3.00,3.00,5.00,3.00,1.00,3.00
75%,0.60,8380.50,1157.00,14.00,4.00,1.0,1557.50,4.00,83.50,3.00,...,4.00,80.0,1.00,15.00,3.00,3.00,9.00,7.00,3.00,7.00
max,1.00,19999.00,1499.00,29.00,5.00,1.0,2068.00,4.00,100.00,4.00,...,4.00,80.0,3.00,40.00,6.00,4.00,40.00,18.00,15.00,17.00

# CODING TASK #5. PANDAS OPERATIONS/FILTERING

In [ ]:
# Let's read a CSV file using Pandas as follows
hr_df = pd.read_csv('Human_Resources.csv')

FileNotFoundError: ignored

In [ ]:
# Pick certain rows that satisfy a certain criteria
loyal_employees_df = hr_df[ (hr_df['YearsAtCompany'] >= 30) ]
loyal_employees_df

NameError: ignored

In [ ]:
# Pick certain rows that satisfy 2 or more critirea

mask_1 = hr_df['YearsAtCompany'] >= 30
mask_2 = hr_df['Department'] == 'Research & Development'

loyal_rnd_df = hr_df[mask_1 & mask_2 ]
loyal_rnd_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
126,58,10312.0,Yes,Travel_Rarely,147,Research & Development,23,4,Medical,1,...,4,80,1,40,3,2,40,10,15,6
190,52,19999.0,No,Travel_Rarely,699,Research & Development,1,4,Life Sciences,1,...,1,80,1,34,5,3,33,18,11,9
270,55,19045.0,No,Travel_Rarely,452,Research & Development,1,3,Medical,1,...,3,80,0,37,2,3,36,10,4,13
473,49,19502.0,No,Travel_Rarely,1245,Research & Development,18,4,Life Sciences,1,...,3,80,1,31,5,3,31,9,0,9
595,58,19246.0,Yes,Travel_Rarely,286,Research & Development,2,4,Life Sciences,1,...,4,80,0,40,2,3,31,15,13,8
653,50,17924.0,No,Non-Travel,881,Research & Development,2,4,Life Sciences,1,...,4,80,1,31,3,3,31,6,14,7
914,55,13577.0,No,Non-Travel,177,Research & Development,8,1,Medical,1,...,4,80,1,34,3,3,33,9,15,0
1086,50,14411.0,No,Travel_Frequently,333,Research & Development,22,5,Medical,1,...,4,80,0,32,2,3,32,6,13,9
1111,53,10169.0,Yes,Travel_Rarely,607,Research & Development,2,5,Technical Degree,1,...,2,80,1,34,4,3,33,7,1,9
1138,50,11245.0,No,Travel_Frequently,1234,Research & Development,20,5,Medical,1,...,3,80,1,32,3,3,30,8,12,13

In [ ]:
# values that fall between a given range
hr_df[hr_df["DailyRate"].between(800, 850)]

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
10,35,2426.0,No,Travel_Rarely,809,Research & Development,16,3,Medical,1,...,3,80,1,6,5,3,5,4,0,3
34,24,2293.0,Yes,Travel_Rarely,813,Research & Development,1,3,Medical,1,...,1,80,1,6,2,2,2,0,2,0
65,55,14756.0,No,Travel_Rarely,836,Research & Development,8,3,Medical,1,...,3,80,3,21,2,3,5,0,0,2
100,37,2073.0,Yes,Travel_Rarely,807,Human Resources,6,4,Human Resources,1,...,4,80,0,7,3,3,3,2,0,2
101,32,2956.0,No,Travel_Rarely,827,Research & Development,1,1,Life Sciences,1,...,4,80,0,1,2,3,1,0,0,0
125,26,2368.0,No,Travel_Rarely,841,Research & Development,6,3,Other,1,...,3,80,0,5,3,2,5,4,4,3
131,50,9208.0,No,Travel_Frequently,809,Sales,12,3,Marketing,1,...,4,80,0,16,3,3,2,2,2,1
133,41,8189.0,No,Travel_Rarely,802,Sales,9,1,Life Sciences,1,...,3,80,1,12,2,3,9,7,0,7
211,30,8474.0,No,Non-Travel,829,Research & Development,1,1,Life Sciences,1,...,3,80,0,12,2,3,11,8,5,8
232,59,2267.0,No,Travel_Rarely,818,Human Resources,6,2,Medical,1,...,4,80,0,7,2,2,2,2,2,2
234,33,2436.0,Yes,Travel_Rarely,813,Research & Development,14,3,Medical,1,...,3,80,1,8,2,1,5,4,0,4
246,33,2911.0,No,Travel_Rarely,832,Research & Development,5,4,Life Sciences,1,...,3,80,1,2,2,2,2,2,0,2
258,51,2723.0,No,Travel_Rarely,833,Research & Development,1,3,Life Sciences,1,...,2,80,0,1,0,2,1,0,0,0
301,18,1200.0,No,Travel_Rarely,812,Sales,10,3,Medical,1,...,1,80,0,0,2,3,0,0,0,0
307,38,12061.0,No,Travel_Rarely,849,Research & Development,25,2,Life Sciences,1,...,3,80,1,19,2,3,10,8,0,1
348,42,15992.0,No,Travel_Rarely,810,Research & Development,23,5,Life Sciences,1,...,2,80,0,16,2,3,1,0,0,0
358,36,6653.0,No,Non-Travel,845,Sales,1,5,Medical,1,...,2,80,0,7,6,3,1,0,0,0
392,54,19406.0,No,Travel_Rarely,821,Research & Development,5,2,Medical,1,...,3,80,1,24,4,2,4,2,1,2
450,31,6582.0,No,Travel_Rarely,828,Sales,2,1,Life Sciences,1,...,3,80,0,10,2,4,6,5,0,5
476,24,2127.0,No,Travel_Rarely,823,Research & Development,17,2,Other,1,...,4,80,1,1,2,3,1,0,0,0
517,25,4851.0,No,Travel_Rarely,810,Sales,8,3,Life Sciences,1,...,3,80,1,4,4,3,3,2,1,2
519,29,2720.0,No,Travel_Frequently,806,Research & Development,1,4,Life Sciences,1,...,4,80,1,10,5,3,10,7,2,8
520,48,8120.0,No,Travel_Rarely,817,Sales,2,1,Marketing,1,...,4,80,0,12,3,3,2,2,2,2
529,38,7625.0,No,Travel_Rarely,827,Research & Development,1,4,Life Sciences,1,...,3,80,0,10,4,2,9,7,1,8
552,56,11103.0,No,Travel_Rarely,832,Research & Development,9,3,Medical,1,...,3,80,0,30,1,2,10,7,1,1
553,40,2342.0,No,Travel_Rarely,804,Research & Development,2,1,Medical,1,...,4,80,0,5,2,2,4,2,2,3
576,27,4342.0,No,Travel_Frequently,829,Sales,8,1,Marketing,1,...,2,80,1,5,3,3,4,2,1,1
589,29,2319.0,Yes,Travel_Rarely,805,Research & Development,1,2,Life Sciences,1,...,4,80,1,1,1,3,1,0,0,0
613,34,3737.0,No,Travel_Rarely,829,Human Resources,3,2,Human Resources,1,...,3,80,1,4,1,1,3,2,0,2
659,28,4908.0,No,Travel_Rarely,821,Sales,5,4,Medical,1,...,2,80,0,4,3,3,4,2,0,2
696,45,4447.0,No,Non-Travel,805,Research & Development,4,2,Life Sciences,1,...,2,80,0,9,5,2,9,7,0,8
715,33,5488.0,No,Travel_Frequently,827,Research & Development,1,4,Other,1,...,1,80,1,6,2,3,6,5,1,2
716,41,19419.0,No,Travel_Frequently,840,Research & Development,9,3,Medical,1,...,2,80,1,21,2,4,18,16,0,11
740,35,3917.0,No,Travel_Rarely,802,Research & Development,10,3,Other,1,...,1,80,1,3,4,2,3,2,1,2
742,50,2380.0,No,Travel_Rarely,804,Research & Development,9,3,Life Sciences,1,...,2,80,0,8,5,3,1,0,0,0
792,33,4508.0,Yes,Travel_Frequently,827,Research & Development,29,4,Medical,1,...,2,80,0,14,4,3,13,7,3,8
846,35,10274.0,No,Travel_Rarely,819,Research & Development,2,3,Life Sciences,1,...,2,80,1,15,2,4,7,7,6,4
856,20,3033.0,No,Travel_Rarely,805,Research & Development,3,3,Life Sciences,1,...,1,80,0,2,2,2,2,2,1,2
932,29,3339.0,Yes,Travel_Rarely,806,Research & Development,7,3,Technical Degree,1,...,1,80,2,10,2,3,7,7,7,7
938,58,2372.0,No,Travel_Rarely,848,Research & Development,23,4,Life Sciences,1,...,4,80,2,2,3,3,2,2,2,2
973,35,5363.0,No,Travel_Rarely,817,Research & Development,1,3,Medical,1,...,2,80,1,10,0,3,9,7,0,0
1055,34,17007.0,No,Travel_Frequently,829,Research & Development,15,3,Medical,1,...,4,80,2,16,3,2,14,8,6,9
1061,24,2033.0,No,Non-Travel,830,Sales,13,2,Life Sciences,1,...,3,80,1,1,2,3,1,0,0,0
1101,32,5878.0,No,Travel_Rarely,824,Research & Development,5,2,Life Sciences,1,...,1,80,1,12,2,3,7,1,2,5
1150,35,5208.0,No,Travel_Rarely,819,Research & Development,18,5,Life Sciences,1,...,4,80,0,16,2,3,16,15,1,10
1177,50,13269.0,No,Travel_Rarely,813,Research & Development,17,5,Life Sciences,1,...,3,80,3,19,3,3,14,11,1,11
1195,49,15379.0,No,Travel_Rarely,809,Research & Development,1,3,Life Sciences,1,...,1,80,0,23,2,3,8,7,0,0
1261,38,5811.0,No,Travel_Rarely,833,Research & Development,18,3,Medical,1,...,3,80,1,15,2,3,1,0,1,0
1262,43,2437.0,Yes,Travel_Frequently,807,Research & Development,17,3,Technical Degree,1,...,4,80,1,6,4,3,1,0,0,0
1285,46,7991.0,No,Non-Travel,849,Sales,26,2,Life Sciences,1,...,3,80,0,6,3,3,2,2,2,2
1300,34,6799.0,No,Travel_Rarely,810,Sales,8,2,Technical Degree,1,...,3,80,2,10,5,3,10,8,4,8
1330,43,19392.0,No,Travel_Rarely,823,Research & Development,6,3,Medical,1,...,4,80,0,21,2,3,16,12,6,14
1335,39,3902.0,No,Travel_Rarely,835,Research & Development,19,4,Other,1,...,2,80,3,7,2,3,2,2,2,2
1336,55,2662.0,No,Travel_Rarely,836,Research & Development,2,4,Technical Degree,1,...,2,80,1,19,2,4,5,2,0,4
1431,32,10422.0,No,Travel_Rarely,801,Sales,1,4,Marketing,1,...,3,80,2,14,3,3,14,10,5,7

In [ ]:
hr_df[hr_df["DailyRate"].between(800, 850)].describe().round(2)

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,55.00,55.00,55.00,55.00,55.00,55.0,55.00,55.00,55.00,55.00,...,55.00,55.0,55.00,55.00,55.00,55.00,55.00,55.00,55.00,55.00
mean,37.65,6579.96,821.00,8.60,2.89,1.0,920.25,2.55,66.75,2.73,...,2.73,80.0,0.76,10.02,2.64,2.76,5.71,4.05,1.40,3.44
std,10.11,5068.57,13.46,7.62,1.10,0.0,589.58,1.05,19.84,0.73,...,1.01,0.0,0.84,7.03,1.25,0.64,4.71,3.98,1.88,3.57
min,18.00,1200.00,801.00,1.00,1.00,1.0,14.00,1.00,33.00,1.00,...,1.00,80.0,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00
25%,31.50,2549.50,809.00,2.00,2.00,1.0,416.00,2.00,49.00,2.00,...,2.00,80.0,0.00,5.00,2.00,2.00,2.00,1.50,0.00,0.50
50%,35.00,4851.00,821.00,6.00,3.00,1.0,816.00,3.00,64.00,3.00,...,3.00,80.0,1.00,9.00,2.00,3.00,4.00,2.00,1.00,2.00
75%,44.00,8331.50,829.50,13.50,4.00,1.0,1427.00,3.00,84.00,3.00,...,3.50,80.0,1.00,15.00,3.00,3.00,9.00,7.00,2.00,6.00
max,59.00,19419.00,849.00,29.00,5.00,1.0,2016.00,4.00,98.00,4.00,...,4.00,80.0,3.00,30.00,6.00,4.00,18.00,16.00,7.00,14.00

**PRACTICE OPPORTUNITY #5 [OPTIONAL]:**
- **Using "hr_df" DataFrame, leverage pandas operations to only select high DailyRate individuals (1450+)**
- **What is the combined Daily Rate for all employees with 1450+?**

**ให้สร้างตัวแปรใหม่ที่ชื่อ high_rate_df**

In [ ]:
high_rate_df = hr_df[ (hr_df['DailyRate'] >= 1450) ]
high_rate_df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
31,44,6465.0,No,Travel_Rarely,1459,Research & Development,10,4,Other,1,...,4,80,0,9,5,4,4,2,1,3
52,44,5454.0,No,Travel_Rarely,1488,Sales,1,5,Marketing,1,...,3,80,1,9,2,2,4,3,1,3
110,51,7484.0,No,Travel_Frequently,1456,Research & Development,1,4,Medical,1,...,3,80,0,23,1,2,13,12,12,8
117,36,9738.0,No,Travel_Frequently,1467,Sales,11,2,Technical Degree,1,...,3,80,1,10,6,3,9,7,2,8
155,29,4319.0,No,Non-Travel,1496,Research & Development,1,1,Technical Degree,1,...,1,80,1,10,1,3,10,7,0,9
164,27,2566.0,No,Non-Travel,1450,Research & Development,3,3,Medical,1,...,4,80,1,1,2,2,1,1,0,1
165,50,19926.0,No,Travel_Rarely,1452,Research & Development,11,3,Life Sciences,1,...,2,80,0,21,5,3,5,4,4,4
172,36,2088.0,No,Travel_Frequently,1480,Research & Development,3,2,Medical,1,...,3,80,0,13,3,2,8,7,7,2
213,51,12490.0,No,Travel_Rarely,1469,Research & Development,8,4,Life Sciences,1,...,4,80,2,16,5,1,10,9,4,7
266,31,5582.0,No,Travel_Rarely,1463,Research & Development,23,3,Medical,1,...,2,80,1,10,2,3,9,0,7,8
278,26,6397.0,No,Travel_Frequently,1479,Research & Development,1,3,Life Sciences,1,...,1,80,1,6,6,1,6,5,1,4
302,28,5661.0,No,Travel_Rarely,1476,Research & Development,16,2,Medical,1,...,3,80,0,9,2,3,8,3,0,7
329,47,18300.0,No,Travel_Rarely,1482,Research & Development,5,5,Life Sciences,1,...,2,80,1,21,2,3,3,2,1,1
373,27,3816.0,No,Travel_Rarely,1469,Research & Development,1,2,Medical,1,...,2,80,1,5,2,3,5,2,0,4
396,43,4522.0,No,Travel_Rarely,1473,Research & Development,8,4,Other,1,...,4,80,0,8,3,3,5,2,0,2
408,52,16555.0,No,Travel_Rarely,1490,Research & Development,4,2,Life Sciences,1,...,4,80,0,31,2,1,5,2,1,4
412,46,4810.0,No,Travel_Rarely,1485,Research & Development,18,3,Medical,1,...,3,80,1,19,5,2,10,7,0,8
416,38,1702.0,No,Travel_Frequently,1490,Research & Development,2,2,Life Sciences,1,...,3,80,1,1,3,3,1,0,0,0
427,60,10266.0,No,Travel_Frequently,1499,Sales,28,3,Marketing,1,...,4,80,0,22,5,4,18,13,13,11
441,42,2093.0,No,Travel_Frequently,1474,Research & Development,5,2,Other,1,...,4,80,1,8,4,3,2,2,2,0
469,32,4707.0,Yes,Non-Travel,1474,Sales,11,4,Other,1,...,4,80,0,6,2,3,4,2,1,2
471,38,9824.0,No,Travel_Rarely,1495,Research & Development,10,3,Medical,1,...,3,80,1,18,4,3,1,0,0,0
665,47,3294.0,No,Travel_Rarely,1454,Sales,2,4,Life Sciences,1,...,1,80,0,3,3,2,3,2,1,2
678,48,2259.0,No,Travel_Rarely,1469,Research & Development,20,4,Medical,1,...,1,80,2,13,2,2,0,0,0,0
691,40,3617.0,No,Travel_Frequently,1469,Research & Development,9,4,Medical,1,...,4,80,1,3,2,3,1,1,0,0
706,40,13194.0,Yes,Non-Travel,1479,Sales,24,3,Life Sciences,1,...,4,80,0,22,2,2,1,0,0,0
766,50,19237.0,No,Travel_Rarely,1464,Research & Development,2,4,Medical,1,...,4,80,1,29,2,2,8,1,7,7
785,40,10322.0,No,Travel_Rarely,1492,Research & Development,20,4,Technical Degree,1,...,4,80,1,14,6,3,11,10,11,1
819,28,3201.0,No,Travel_Rarely,1451,Research & Development,2,1,Life Sciences,1,...,1,80,0,6,2,1,5,3,0,4
842,28,2515.0,Yes,Travel_Rarely,1485,Research & Development,12,1,Life Sciences,1,...,4,80,0,1,4,2,1,1,0,0
854,45,4477.0,No,Travel_Rarely,1457,Research & Development,7,3,Medical,1,...,3,80,1,7,2,2,3,2,0,2
869,46,19081.0,No,Travel_Rarely,1450,Research & Development,15,2,Life Sciences,1,...,1,80,1,25,2,3,4,2,0,3
886,30,3579.0,No,Travel_Rarely,1465,Research & Development,1,3,Medical,1,...,1,80,1,12,2,3,11,9,5,7
944,28,6674.0,No,Non-Travel,1476,Research & Development,1,3,Life Sciences,1,...,1,80,3,10,6,3,9,8,7,5
986,39,6120.0,No,Travel_Rarely,1498,Sales,21,4,Life Sciences,1,...,4,80,2,8,2,4,5,4,1,4
992,39,10920.0,No,Non-Travel,1485,Research & Development,25,2,Life Sciences,1,...,2,80,1,13,2,3,6,4,0,5
1001,37,3629.0,No,Travel_Rarely,1462,Research & Development,11,3,Medical,1,...,1,80,0,8,6,3,3,2,0,2
1006,49,4284.0,Yes,Travel_Frequently,1475,Research & Development,28,2,Life Sciences,1,...,1,80,0,20,2,3,4,3,1,3
1025,24,4162.0,No,Travel_Rarely,1476,Sales,4,1,Medical,1,...,3,80,2,5,3,3,5,4,0,3
1044,49,6651.0,No,Travel_Rarely,1495,Research & Development,5,4,Technical Degree,1,...,2,80,1,20,0,2,3,2,1,2
1046,44,3420.0,No,Travel_Rarely,1467,Research & Development,20,3,Life Sciences,1,...,3,80,0,6,3,2,5,2,1,3
1054,49,10466.0,No,Travel_Rarely,1490,Research & Development,7,4,Life Sciences,1,...,2,80,2,29,3,3,8,7,0,7
1056,28,2909.0,Yes,Travel_Frequently,1496,Sales,1,3,Technical Degree,1,...,4,80,1,5,3,4,3,2,1,2
1124,39,8237.0,No,Travel_Rarely,1462,Sales,6,3,Medical,1,...,1,80,1,11,3,3,7,6,7,6
1163,37,3936.0,No,Travel_Rarely,1470,Research & Development,10,3,Medical,1,...,1,80,1,8,2,1,8,4,7,7
1202,38,3306.0,No,Travel_Rarely,1495,Research & Development,4,2,Medical,1,...,4,80,1,7,5,2,0,0,0,0
1236,36,6134.0,Yes,Travel_Rarely,1456,Sales,13,5,Marketing,1,...,2,80,3,16,3,3,2,2,2,2
1342,34,9713.0,No,Travel_Rarely,1480,Sales,4,3,Life Sciences,1,...,4,80,3,9,3,3,5,3,1,0
1369,28,9854.0,Yes,Travel_Rarely,1475,Sales,13,2,Marketing,1,...,4,80,0,6,0,3,2,0,2,2
1422,35,2660.0,No,Travel_Rarely,1490,Research & Development,11,4,Medical,1,...,3,80,1,5,3,3,2,2,2,2

In [ ]:
high_rate_df['DailyRate'].sum()

73749

# CODING TASK #6: PERFORM BASIC EDA ON BOTH CLASSES

In [ ]:
hr_df

In [ ]:
hr_df.info()

In [ ]:
# It makes sense to drop 'EmployeeCount', 'Standardhours' and 'Over18' since they do not change from one employee to the other
# Let's drop 'EmployeeNumber' as well
hr_df.drop(['EmployeeCount', 'StandardHours', 'Over18', 'EmployeeNumber'], axis=1, inplace=True)

In [ ]:
hr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   MonthlyIncome             1467 non-null   float64
 2   Attrition                 1470 non-null   object
 3   BusinessTravel            1470 non-null   object
 4   DailyRate                 1470 non-null   int64
 5   Department                1469 non-null   object
 6   DistanceFromHome          1470 non-null   int64
 7   Education                 1470 non-null   int64
 8   EducationField            1469 non-null   object
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1469 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1469 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1469 non-null   object
 17  MonthlyRate               1468 non-null   float64
 18  NumCompaniesWorked        1470 non-null   int64
 19  OverTime                  1470 non-null   object
 20  PercentSalaryHike         1469 non-null   float64
 21  PerformanceRating         1469 non-null   float64
 22  RelationshipSatisfaction  1470 non-null   int64
 23  StockOptionLevel          1470 non-null   int64
 24  TotalWorkingYears         1470 non-null   int64
 25  TrainingTimesLastYear     1470 non-null   int64
 26  WorkLifeBalance           1470 non-null   int64
 27  YearsAtCompany            1470 non-null   int64
 28  YearsInCurrentRole        1470 non-null   int64
 29  YearsSinceLastPromotion   1470 non-null   int64
 30  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(4), int64(19), object(8)
memory usage: 356.1+ KB

In [ ]:
# Let's see how many employees left the company!
left_df = hr_df[hr_df['Attrition'] == 'Yes']

In [ ]:
# View employees who left
left_df

In [ ]:
left_df.describe()

**PRACTICE OPPORTUNITY #6 [OPTIONAL]:**
- **Filter the hr_df to only include the employees who stayed in the company**
- **Generate statistical summary for employees who stayed**
- **Compare both statistical summaries. What do you infer from the data?**

# CODING TASK #7. PANDAS WITH FUNCTIONS

In [ ]:
# Let's read a CSV file using Pandas as follows
hr_df = pd.read_csv('Human_Resources.csv')
hr_df

In [ ]:
# Let's assume the daily rate has increased by 10%
# Define a function that increases all clients networth by a fixed value of 10% (for simplicity sake)
def dailyrate_update(balance):
    return balance * 1.1 # assume that net worth increased by 10%

In [ ]:
# You can apply a function to the DataFrame
hr_df['DailyRate'] = hr_df['DailyRate'].apply(dailyrate_update)
hr_df

**PRACTICE OPPORTUNITY #7 [OPTIONAL]:**
- **Define a function that doubles the DailyRate and adds $100**
- **Apply the function to the DataFrame**
- **Calculate the updated total Daily Rate of all employees combined**

# CODING TASK #8: HISTOGRAM AND CORRELATION

In [ ]:
hr_df.hist(bins = 30, figsize = (20,20), color = 'r');
# Several features such as 'MonthlyIncome' and 'TotalWorkingYears' are tail heavy

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
correlations = hr_df.corr()
f, ax = plt.subplots(figsize = (20, 20))
sns.heatmap(correlations, annot = True)
# Job level is strongly correlated with total working hours
# Monthly income is strongly correlated with Job level
# Monthly income is strongly correlated with total working hours
# Age is strongly correlated with monthly income

**PRACTICE OPPORTUNITY #8 [OPTIONAL]:**
- **Change the color of the heatmap [External Research is Required]**

In [ ]:
import numpy as np
correlations = hr_df.corr()
f, ax = plt.subplots(figsize = (20, 20))
sns.heatmap(correlations, cmap="YlGnBu", annot = True);

# FINAL CAPSTONE PROJECT OVERVIEW

- In this project, we will perform basic Exploratory Data Analysis (EDA) on the Kyphosis disease Dataset.
- Kyphosis is an abnormally excessive convex curvature of the spine.
- Dataset contains 81 rows and 4 columns representing data on children who have had corrective spinal surgery.
    - INPUTS: 1. Age: in months, 2. Number: the number of vertebrae involved, 3. Start: the number of the first (topmost) vertebra operated on.
    - OUTPUTS: Kyphosis which represents a factor with levels absent present indicating if a kyphosis (a type of deformation) was present after the operation.
- Using the “kyphosis.csv" included in the course package, write a python script to perform the following tasks:
    1. Import the “kyphosis.csv" file using Pandas
    2. Perform basic Exploratory Data Analysis (EDA) on the data
    3. List the average, minimum and maximum age (in years) considered in this study using 2 methods
    4. Plot the correlation matrix
    5. Convert the age column datatype from int64 to float64
    6. Define a function that converts age from months to years
    7. Apply the function to the “Age” column and add the results into a new column entitled “Age in Years”
    8. What are the features of the oldest and youngest child in this study?
    9. Scale the raw Age column (in months) using both standardization and Normalization. Perform a sanity check.